<?php

namespace Squarebit\Volition\Tests;

use AllowDynamicProperties;
use Barryvdh\Snappy\Facades\SnappyPdf;
use Domains\Core\Database\Factories\UserFactory;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Tests\CreatesApplication;

#[AllowDynamicProperties]
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Http::preventStrayRequests();
        Mail::fake();
        SnappyPdf::fake();
        Storage::fake();

        $this->actingAs(UserFactory::new()->create());
    }
}
